import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/SessionProvider'
import Navbar from '@/components/Dashboard/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <body className={`your-existing-classes ${inter.className} p-10 flex flex-col gap-10 h-full transition-all duration-300 ease-in-out md:p-4 md:gap-4`}>
        <AuthProvider>
          <Navbar />
        {children}
        </AuthProvider>
        </body>
    </html>
  )
}
